services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3000:3000
    networks:
      - strapi
networks:
  strapi:
    name: Strapi
    driver: bridge
    external: true