version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - strapi
networks:
  strapi:
    name: Strapi
    driver: bridge