FROM node:18-alpine3.18

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production && yarn cache clean && yarn global add serve

RUN yarn add typescript --dev

COPY . .



RUN yarn build
EXPOSE 3000

CMD ["serve", "-s", "dist"]